---
abstract: 'Detect leaked callbacks'
author:
  - 'Mons Anderson, C<< <mons at cpan.org> >>'
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  lib::abs: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Leak-Cb
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Devel::Leak::Cb:
    file: lib/Devel/Leak/Cb.pm
    version: 0.04
recommends:
  Devel::FindRef: 0
  Devel::Refcount: 0
  Sub::Identify: 0
  Sub::Name: 0
requires:
  Devel::Declare: 0.005011
  common::sense: 2
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
